CREATE TABLE kullanici (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kullanici_adi VARCHAR(255) NOT NULL UNIQUE,
    sifre         VARCHAR(255) NOT NULL,
    ad_soyad      VARCHAR(255) NOT NULL,
    rol           VARCHAR(20)  NOT NULL CHECK (rol IN ('ADMIN', 'PERSONEL')),
    durum         VARCHAR(20)  NOT NULL CHECK (durum IN ('AKTIF', 'PASIF')),
    kayit_tarih   TIMESTAMP(6) NOT NULL
);

CREATE TABLE refresh_token (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kullanici_id BIGINT       NOT NULL REFERENCES kullanici (id),
    token        VARCHAR(512) NOT NULL UNIQUE,
    expiry_date  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revoked      BOOLEAN      NOT NULL
);

CREATE TABLE grup (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad VARCHAR(255) NOT NULL
);

CREATE TABLE saha (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad            VARCHAR(255)   NOT NULL,
    durum         VARCHAR(20)    NOT NULL CHECK (durum IN ('AKTIF', 'PASIF')),
    saatlik_ucret NUMERIC(10, 2) NOT NULL
);

CREATE TABLE urun (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad    VARCHAR(255)   NOT NULL,
    adet  INTEGER        NOT NULL,
    fiyat NUMERIC(10, 2) NOT NULL
);

CREATE TABLE ogrenci (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grup_id               BIGINT         REFERENCES grup (id),
    ad_soyad              VARCHAR(255)   NOT NULL,
    dogum_tarih           DATE,
    veli_ad_soyad         VARCHAR(255),
    veli_tel_no           VARCHAR(255),
    durum                 VARCHAR(20)    NOT NULL CHECK (durum IN ('AKTIF', 'PASIF')),
    antrenman_gun_sayisi  INTEGER,
    aylik_aidat           NUMERIC(10, 2),
    odeme_durumu          VARCHAR(20)    NOT NULL CHECK (odeme_durumu IN ('ODENDI', 'ODENMEDI', 'KISMI_ODENDI')),
    odeme_plani           VARCHAR(255),
    odenen_donem          VARCHAR(255),
    odeme_tarihi          DATE,
    sonraki_odeme_tarih   DATE,
    odenen_tutar          NUMERIC(10, 2),
    odeme_sekli           VARCHAR(20)    CHECK (odeme_sekli IN ('NAKIT', 'KART', 'HAVALE_EFT')),
    kayit_tarih           TIMESTAMP(6)   NOT NULL,
    "not"                 VARCHAR(255)
);

CREATE TABLE rezervasyon (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saha_id        BIGINT         NOT NULL REFERENCES saha (id),
    ad_soyad       VARCHAR(255)   NOT NULL,
    baslangic_tarih TIMESTAMP(6)  NOT NULL,
    bitis_tarih    TIMESTAMP(6)   NOT NULL,
    durum          VARCHAR(20)    NOT NULL CHECK (durum IN ('AKTIF', 'IPTAL')),
    tel_no         VARCHAR(255)   NOT NULL,
    odeme_yontemi  VARCHAR(20)    CHECK (odeme_yontemi IN ('NAKIT', 'KART', 'HAVALE_EFT')),
    odeme_durumu   VARCHAR(20)    NOT NULL CHECK (odeme_durumu IN ('ODENDI', 'ODENMEDI', 'KISMI_ODENDI')),
    odenecek_tutar NUMERIC(10, 2) NOT NULL
);

CREATE TABLE rezervasyon_urun (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rezervasyon_id BIGINT  NOT NULL REFERENCES rezervasyon (id),
    urun_id        BIGINT  NOT NULL REFERENCES urun (id),
    miktar         INTEGER NOT NULL
);
